---
- name: update apt 
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  tags: bootstrap

- name: create group for zookeeper
  group:
    name: zookeeper
    state: present
  tags: zookeeper

- name: create user for zookeeper
  user:
    name: zookeeper
    group: zookeeper
  tags: zookeeper

- name: setup for zookeper download path
  set_fact:
    zookeeper_name: zookeeper-{{ zookeeper.version }}
  tags: zookeeper

- name: setup for zookeeper download dir
  set_fact:
    zookeeper_dir: "{{ zookeeper.install_dir }}/{{ zookeeper_name }}"
  tags: zookeeper

- name: Copy Zookeeper tar file
  copy:
    src: "../files/{{ zookeeper_name }}.tar.gz"
    dest: "{{ zookeeper.download_dir }}/{{ zookeeper_name }}.tar.gz"
    owner: vagrant
    mode: 0644
  tags: zookeeper

- name: untar zookeeper
  shell: tar -xzvf {{ zookeeper.download_dir }}/{{ zookeeper_name }}.tar.gz chdir={{ zookeeper.download_dir }}/ creates={{ zookeeper.download_dir }}/{{ zookeeper_name }}
  tags: zookeeper

- name: setup config file
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper.download_dir }}/{{ zookeeper_name }}/conf/zoo.cfg"
    force: yes
  tags: zookeeper

- name: change config file permission
  shell: chmod 0644 {{ zookeeper.download_dir }}/{{ zookeeper_name }}/conf/zoo.cfg
  tags: zookeeper

- name: Copy zookeeper to  destination
  shell: mv {{ zookeeper.download_dir }}/{{ zookeeper_name }} {{ zookeeper_dir }} creates={{ zookeeper_dir }}
  tags: zookeeper

- name: check zookeeper data dir
  stat: path={{ zookeeper.data_dir }}
  register: check_path
  tags: zookeeper

- shell: mkdir -p {{ zookeeper.data_dir }}
  when: check_path.stat.exists == false
  tags: zookeeper

- name: configure myid file
  template:
    src: myid.j2
    dest: "{{ zookeeper.data_dir }}/myid" 
  tags: zookeeper

- name: Link {{ zookeeper.install_dir }}/zookeeper to this version
  shell: ln -s {{ zookeeper_name }} zookeeper chdir={{ zookeeper.install_dir}} creates={{ zookeeper.install_dir }}/zookeeper
  tags: zookeeper

- name: copy zookeeper service file
  template:
    src: zookeeper-service.j2
    dest: "/etc/init.d/zookeeper"
    mode: 0755
  notify: start zookeeper
  tags: zookeeper

- name: start zookeeper
  service: name=zookeeper state=started
  tags: zookeeper

- name: copy zookeeper service cron
  template:
    src: zookeeper-check.sh.j2
    dest: "/home/vagrant/zookeeper-check.sh"
    mode: 0777
  tags: zookeeper

- name: copy zookeeper mail file
  template:
    src: email_text_zookeeper.txt.j2
    dest: "/home/vagrant/email_text_zookeeper.txt"
    mode: 0777
  tags: zookeeper


- name: set zookeeper service check cron
  cron:
    name: "zookeeper check"
    job: "/bin/bash /home/vagrant/zookeeper-check.sh"
  tags: zookeeper

