---
- name: update cache
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  

- name: create group for kafka
  group:
    name: kafka
    state: present
  tags: kafka

- name: create user for kafka
  user:
    name: kafka
    group: kafka
  tags: kafka

- name: setting kafka name
  set_fact:
    kafka_name: kafka_{{ kafka.scala_version }}-{{ kafka.version }}
  tags: kafka

- name: Setting kafka directory
  set_fact:
    kafka_dir: "{{ kafka.install_dir }}/{{ kafka_name }}"
  tags: kafka

- name: check kafka tar file
  command: test -f {{ kafka.download_dir }}/{{ kafka_name }}.tgz
  register: kafka_tar_downloaded
  failed_when: kafka_tar_downloaded.rc not in [0, 1]
  changed_when: False
  tags: kafka

- name: confirm kafka tar file download
  get_url:
    url: "{{ kafka.mirror }}/kafka/{{ kafka.version }}/{{ kafka_name }}.tgz"
    dest: "{{ kafka.download_dir }}"
  tags: kafka
  when: kafka_tar_downloaded.rc == 1

- name: extract kafka tar file
  command: tar -zxf {{ kafka.download_dir }}/{{ kafka_name }}.tgz chdir={{ kafka.install_dir }}
  tags: kafka

- name: check kafka data dir
  file:
    path: "{{ kafka.data_dir }}"
    state: directory
    owner: kafka
    group: kafka
  tags: kafka

- name: copy kafka config file
  template:
    src: kafka-properties.j2
    dest: "{{ kafka_dir }}/config/{{ kafka.server_properties }}"
  tags: kafka

- name: create kafka symlink
  shell: ln -s {{ kafka_name }} kafka chdir={{ kafka.install_dir }} creates={{ kafka.install_dir }}/kafka
  tags: kafka


- name: check zookeeper client port 
  wait_for:
    host: "{{ groups['zookeepers'][0] }}"
    port: "{{ zk_client_port }}"
    delay: 5
    timeout: 15
  tags: kafka

- name: install kafka service handler file
  template: 
    src: kafka-service.j2
    dest: "/etc/init.d/kafka"
    mode: 0755
  notify: start kafka
  tags: kafka

- name: start kafka service
  service: name=kafka state=started
