---
- hosts: zookeepers
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - {
        role: java, 
        when: accept_oracle_licence
      }
    - {
        role: zookeeper,
        zookeeper_version: 3.4.10
      }
- hosts: kafka-nodes
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - {
        role: java, 
        when: accept_oracle_licence
      }
    - {
        role: kafka
      }
